### ISSUE TITLE
Incompatible with lilypond 2.18.2

### ISSUE THREAD

**Issue by wenkokke** [music-suite/music-suite#1]
When running lilypond on a music-suite generated .ly file, lilypond reports:

```
GNU LilyPond 2.18.2
Processing `/usr/local/share/lilypond/2.18.2/ly/init.ly'
Parsing...
/usr/local/share/lilypond/2.18.2/ly/init.ly:40:1: error: \maininput not allowed outside init files

\maininput
/usr/local/share/lilypond/2.18.2/ly/init.ly:1: warning: no \version statement found, please add

\version "2.18.2"

for future compatibility
/usr/local/share/lilypond/2.18.2/ly/init.ly:1: warning: no \version statement found, please add

\version "2.18.2"

for future compatibility
fatal error: failed files: "init.ly"
```

Which version of lilypond is used with music-suite development? Which lilypond versions are supported at the moment?

**Comment by hanshoglund** [comment]
Current version of music-score works with 2.16 (and possibly 2.17), I will upgrade to the latest version for the next release.

If you can find a workaround or fix please write back. Pull requests always welcome of course.
