### ISSUE TITLE
String Fingerings

### ISSUE THREAD

**Issue by olynch** [music-suite/music-suite#19]
Hello,

I am wondering if it is possible to notate string fingerings in this library, or how I would approach adding them if they aren't already in.

-Owen

**Comment by hanshoglund** [comment]
Hi Owen,

It's not currently supported. The way to go about it would be to add another record field named `stringFingering` to the `SomeTechnique` type, a high level wrapper similar to `pizz`, `arco`, `sulPont`, and corresponding export handlers for for XML/Lilypond in `Music.Score.Export`.

Note @jmorag is working on something similar over here: https://github.com/hanshoglund/music-suite/issues/20

**Comment by olynch** [comment]
OK, I've read the source and I know how it works in musicxml, so I have a chance of getting it right. I'm going to close this.
