### ISSUE TITLE
Use in External Project

### ISSUE THREAD

**Issue by olynch** [music-suite/music-suite#28]
How would I use this as a library in an external project? I'm using nix in the external project, so theoretically it should all work, but I'm not really sure how this is packaged, especially because it isn't on hackage. I guess I could add this as a submodule and then use a multi-project cabal setup, but that seems a little weird.

**Comment by jwaldmann** [comment]
generally (not specific for music-suite)

with stack:
* in the cabal file: build-depends: music-suite  
* in stack.yaml: extra-dep: (URL and commit of this repo)

(I do this often)

with cabal, second step can be done via `cabal.project` file (but I'm not used to it)

**Comment by olynch** [comment]
There are a good number of dependencies of music-suite that don't work with recent stackages... In any case, I ended up doing a multi-project cabal.

It would be nice if this was better packaged, but that's a lot of work so it's understandable that it hasn't been done yet.

**Comment by jwaldmann** [comment]
> good number of dependencies of music-suite that don't work with recent stackages

This sort-of-works for me: https://github.com/jwaldmann/music-suite/blob/master/stack.yaml

sort-of, because there are some errors (in music-suite, not in dependencies) due to using a recent ghc.
