### ISSUE TITLE
build and test with ghc-8.8 and stack

### ISSUE THREAD

**Issue by jwaldmann** [music-suite/music-suite#30]
FYI, f1be137fe99588e39f17336dcf8f693b662acf41

```
PATH=/opt/ghc/ghc-8.8.4/bin:$PATH stack --resolver=lts-16.15 test
...
All 108 tests passed (1.39s)
music-suite> Test suite music-suite-test-laws passed
...
UTMS export done
  Number of errors: 20
music-suite> Test suite music-suite-test-umts passed
...
All 126 tests passed (0.18s)

music-suite> Test suite music-suite-test-xml-parser passed
```
It seems that `stack` insists on build all executables (before running tests).
With `ghc-options: -fno-code` , it will  fail on installing the executables,
and run no tests.

**Comment by jwaldmann** [comment]
works for ghc-8.10 as well (same outputs) after 44a546df305497f8028435f7f090939246e56012 (#33)

**Comment by hanshoglund** [comment]
Hi @jwaldmann! I think my comments on #33 applies here too!
