### ISSUE TITLE
[with ghc-8.10] Music.Score.Pitch is missing Safe Haskell mode

### ISSUE THREAD

**Issue by jwaldmann** [music-suite/music-suite#32]
when compiling with ghc-8.10.2, I get
```
...
[ 75 of 129] Compiling Music.Score.Pitch

..../music-suite/src/Music/Score/Pitch.hs:1:1: error: [-Wmissing-safe-haskell-mode, -Werror=missing-safe-haskell-mode]
    Music.Score.Pitch is missing Safe Haskell mode
  |
1 | {-# LANGUAGE DerivingStrategies #-}
  | ^
```
and some funny follow-up messages
```
..../music-suite/src/Music/Score/Pitch.hs:99:8: error: [-Wprepositive-qualified-module, -Werror=prepositive-qualified-module]
    Found ‘qualified’ in prepositive position
    Suggested fix: place  ‘qualified’ after the module name instead.
   |
99 | import qualified Data.List
   |        ^^^^^^^^^
```
I can remove `-Werror` from `{-# OPTIONS_GHC ` as as work-around.

**Comment by jwaldmann** [comment]
I had never seen `prepositive` (https://gitlab.haskell.org/ghc/ghc/-/issues/18545) I think it's implied by `-Weverything`.

**Comment by hanshoglund** [comment]
Hi @jwaldmann. I think my comments on #33 applies here as well.

**Comment by hanshoglund** [comment]
@jwaldmann I am unable to reproduce this on the #55 branch. Could you share the exact invocation please?

**Comment by hanshoglund** [comment]
Closing as GHC has been upgraded to 8.10.4 and the build succeeds in CI.
