### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by cianoc** [music-suite/music-suite#53]
I really like this project and am glad that it is now working again. This is the closest I've ever found to my ideal composition process/workflow. I'm in awe of all the work that has gone into this.

However I've noticed that this project still has a number of rough spots.
1) No stack implementation. This makes it impossible to build the system currently on anything other than Linux.
2) Incomplete documentation. I think guide.md is the latest version of the documentation, though it's incomplete. The official website seems to be extremely old and the examples don't seem to work any more.
3) Functionality that seems to have stopped working? E.g. I can't quite work out how to export to SuperCollider. 
4) Tooling - quite a few of the tools either don't work for me (possibly an OSX thing), or have just stopped working.

I like this project a lot, and so I'd like to try and help with some of these things if I can, but I'm not sure what your vision for it is and how compatible it is with what I want.

**Stack Implementation**
I have a working stack build. I have zero experience with Continuation Integration, but I'd be happy to do what I can to help to push this over the finish line. 

**Documentation**
I think the documentation you have is mostly pretty good, it's just incomplete/out of date. For the website it seems like the vision of the project has changed since you originally started the project, so I wouldn't feel confident making changes on that without understanding what music-suite is supposed to be now. The more up to date documentation is I think the guide.md document, which I think it would be useful to reference? Though that seems incomplete.

Something I do think would be helpful would be to have some documentation that targets composers who are not Haskell developers, but who are willing to learn lilypond. Currently it seems very Haskell based (lot of type theory, which seems quite advanced), which seems quite limiting.

I'd be happy to help with some of this stuff if that's useful.

**Functionality**
I feel a lot of this might just be updating the documentation to provide deals on how this stuff should work now, or simply removing references. I'd be happy to do some of that pruning if it's helpful.

**Vision**
How do you expect people to use this framework? I've found in practice that it works best for me as a library dependency in a new project where I build my piece. But it seems that your expectation is more that this is more of a framework?

**Possible Enhancements**
- I'd really like to get this working with guido (for interactive work with inscore), the excellent csound-expression libraries (and maybe get the supercollider stuff working again if that's an issue). 
- I think something that allowed one to easily play midi files from the repl interactively would be great. 
- I have a little watcher utility that interactively compiles my haskell scores into lilypond which has been very useful.
- I also have a few functions which I've written which might be useful (nothing amazing - just little useful compositional stuff), and I'll probably continue to grow. Are those kinds of contributions welcome?

**Comment by hanshoglund** [comment]
Hi @cianoc I'm glad to hear you like Music Suite!

> Stack Implementation

This has been discussed in #33 and #55. In brief, I'm open to PRs adding support for Stack, as long as current way of building with Cabal must also be supported. 

>  composers who are not Haskell developers, but who are willing to learn lilypond. 

There is ongoing work on rehauling the documentation in `docs/src/User-Guide.md` to be more friendly to non-Haskellers. I would recommend starting with this file.

There is a related effort to build the documentation with Sphinx/Read-the-docs. See `docs-sphinx/README.md`. An outstanding work item is to generate these new HTML docs automatically and point the website to them.

In general, I'm extremely supportive of merging documentation work, examples and beginner-oriented tutorials. 

>  How do you expect people to use this framework? I've found in practice that it works best for me as a library dependency in a new project where I build my piece. But it seems that your expectation is more that this is more of a framework?

Currently, the only supported way to use Music Suite is to:
- Clone this repo
- Build the library using `cabal build`
- Import music suite into another Haskell module or REPL session.

This will continue to be supported. I think it would be great if there were also more beginner-friendly paths to using Music Suite, similar to what you get with Max, Supercollider etc. 

> I'd really like to get this working with guido (for interactive work with inscore)

This I foresee being a *big* work item (including supporting the Guide representation, linking etc). I would recommend starting with something smaller!

> the excellent csound-expression libraries (and maybe get the supercollider stuff working again if that's an issue)

Contributions in this direction are certainly welcome. Again I would advise starting with something small :D. We used to have bindings to SuperCollider, but these are not present in the current code-base (any remaining reference to them in the documentation is accidental). I'm however quite familiar with SuperCollider, and happy to mentor any efforts to revive them, or to integrate Csound.

**Comment by cianoc** [comment]
> There is ongoing work on rehauling the documentation in docs/src/User-Guide.md to be more friendly to non-Haskellers. I would recommend starting with this file.

Thanks! I spent quite a lot of time reading through this this weekend and it was extremely helpful. Happy to see if there are ways I can help improve it.

> There is a related effort to build the documentation with Sphinx/Read-the-docs. See docs-sphinx/README.md. An outstanding work item is to generate these new HTML docs automatically and point the website to them.

Ah good to know. Not sure how helpful I can be here, but I'd be happy to at least have a look at that.

> This I foresee being a big work item (including supporting the Guide representation, linking etc). I would recommend starting with something smaller!

Fair. The Guido representation is fairly straightforward (I've written generators in SuperCollider and Rust), but the rest is possibly less so :) Maybe I should wait until I have a better understanding of the Music Suite library.

> We used to have bindings to SuperCollider, but these are not present in the current code-base (any remaining reference to them in the documentation is accidental). I'm however quite familiar with SuperCollider, and happy to mentor any efforts to revive them, or to integrate Csound.

I'd be happy to revive the SuperCollider stuff if you could point me in the right direction. Did it generate a non-RT score directly, or did it use hsc3?

**Comment by hanshoglund** [comment]
@cianoc I've split off the discussion on new audio backends into a separate issue: #56.

I believe I've answered your other questions, so I'll close this. Feel free to open new tickets though.
