### ISSUE TITLE
A lot of the example files are empty, or just notes for pieces

### ISSUE THREAD

**Issue by cianoc** [music-suite/music-suite#61]
I was wondering if you'd be okay with me going through and cleaning up all the examples that are either notes for pieces you plan to write, or just empty bits of code?

**Comment by cianoc** [comment]
All the pieces that should be removed are in 'pieces' subdirectory'. These are the files I would suggest removing (I'm happy to do this as a pull request if you approve this):
[BrassChords](https://github.com/music-suite/music-suite/blob/master/examples/pieces/BrassChords/Score.hs)
[Canons](https://github.com/music-suite/music-suite/blob/master/examples/pieces/Canons/Score.hs)
[FixedPitches](https://github.com/music-suite/music-suite/blob/master/examples/pieces/FixedPitches/Score.hs)
[Holst](https://github.com/music-suite/music-suite/tree/master/examples/pieces/Holst/Score.hs)
[Ostinati](https://github.com/music-suite/music-suite/blob/master/examples/pieces/Ostinati/Score.hs)
[Piece1](https://github.com/music-suite/music-suite/tree/master/examples/pieces/Piece1)
[Piece2](https://github.com/music-suite/music-suite/tree/master/examples/pieces/Piece2)
[Piece3](https://github.com/music-suite/music-suite/tree/master/examples/pieces/Piece3)
[Piece4](https://github.com/music-suite/music-suite/tree/master/examples/pieces/Piece4)
[PopChords](https://github.com/music-suite/music-suite/blob/master/examples/pieces/PopChords/Score.hs)
[TreeOfRhythms](https://github.com/music-suite/music-suite/blob/master/examples/pieces/TreeOfRhythms/Score.hs)
[VlaPno](https://github.com/music-suite/music-suite/blob/master/examples/pieces/VlaPno/Score.hs)

All the pieces that start with a Z.

[Piece 1.txt](https://github.com/music-suite/music-suite/blob/master/examples/pieces/Piece1.txt)
[Piece 6.hs](https://github.com/music-suite/music-suite/blob/master/examples/pieces/Piece6.hs)
[Piece 7.hs](https://github.com/music-suite/music-suite/blob/master/examples/pieces/Piece7.hs)
[Piece 9.hs](https://github.com/music-suite/music-suite/blob/master/examples/pieces/Piece9.hs)
[Piece 10.hs](https://github.com/music-suite/music-suite/blob/master/examples/pieces/Piece10.hs)
[Piece 11.hs](https://github.com/music-suite/music-suite/blob/master/examples/pieces/Piece11.hs)
[Piece 12.hs](https://github.com/music-suite/music-suite/blob/master/examples/pieces/Piece12.hs)

Possibly TODO as well:
[TODO](https://github.com/music-suite/music-suite/blob/master/examples/pieces/TODO)

**Comment by hanshoglund** [comment]
I'd be happy to merge your PR :)
