### ISSUE TITLE
Thaw dependencies?

### ISSUE THREAD

**Issue by kindaro** [music-suite/music-suite#89]
Dependencies being frozen hinders my work with this package.

I do not have Nix and I also do not have GHC 8.10.4. _(I do not have enough free space to install yet another compiler and re-build all dependencies with it. I only keep the latest of each major version of GHC.)_ I had to remove the freeze file and modify a few lines of code to get it to work with GHC 8.10.7. Since it now works, I say freezing all dependencies is not unavoidable.

So, please consider supporting the common way to build this package — let Cabal solve the dependency graph. It may need some work to set version bounds where needed, but in my case it was only a few lines.

I can help out.

**Comment by hanshoglund** [comment]
Hello @kindaro,

It sounds the main source of your pain is that the compiler patch version. I upgraded it to 8.10.7 in #90. You should be able to build the current main branch with the compiler you have installed.

I'd like the main CI build to remain reproducible (by which I mean that the pass/fail status of each commit is stable). Are there ways of achieving that without using a freeze file?

**Comment by kindaro** [comment]
Stable along what dimension, according to which observations?

Without freezing there are many ways for the world to throw a wrench into the gearbox. I advise freezing on industrial, closed source, executable-centered projects. But is it warranted for an innovative open source library?

Freeze files do not work when the library is seen as a package. For example, I currently have a Haskell project in directory `X` that includes a package in directory `X` where I do stuff and the package `music-suite` in directory `Y` that I depend on. The project configuration inside `Y` is ignored in this arrangement. Freeze or no freeze, the project configuration in `X` decides everything.

I have already solved my problem, so for me it is fine either way.

**Comment by hanshoglund** [comment]
> Stable along what dimension, according to what observations?

Time; that the build is successful on any supported machine.

Note that supported means Linux atm, we do not have a CI story for alternative platforms.

I am open to merging alternative CI setups/jobs as long the author is prepared to maintain them and the current reproducible (Nix-based) build continues to work.

> I currently have a Haskell project in directory X that includes a package in directory X where I do stuff and the package music-suite in directory Y that I depend on

In this case there is no need to remove the freeze files (they are ignored as you say), but you may want to have the constraints in the Cabal file. Feel free to make a PR adding those.

**Comment by hanshoglund** [comment]
I've spun off OS X/Windows CI as separate tickets #101 #102

Closing this. Feel free to reopen if there is outstanding discussion/work.

**Comment by kindaro** [comment]
> I am open to merging alternative CI setups/jobs as long the author is prepared to maintain them and the current reproducible (Nix-based) build continues to work.

This latter condition unfortunately means that I cannot contribute anything. I used to have Nix on my computer, but it takes too much space — eventually I had to remove it. This means that I cannot apply my Haskell skill to this project. I can handle freeze files, but Nix is too much.

I am not sure how you expect this project to be used. My idea was to depend on it as a usual Cabal library, so that I can build my own executable that emits music. In this arrangement Nix and even Cabal project files are irrelevant. If this case is not supported, then I do not see how I should use this project.

**Comment by hanshoglund** [comment]
Note that Nix is only used to pin GHC and runtime dependencies. You can also [install these via ghcup](https://github.com/music-suite/music-suite#manual-setup). 

This works and we've had contributions from non-Nix users using this install method. It is however not "fully supported" as we lack a CI setup (#100 #101 #102).

**Comment by kindaro** [comment]
I see, so the best way for me to go is add that continuous integration and thereby legitimize any possible further contributions.

**Comment by hanshoglund** [comment]
That would be great :).
